version: "3"

services:
  python-app:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    extra_hosts:
      - ethics-sftp-ui_mongodb_1:172.17.0.1
    restart: unless-stopped

  react-app:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - python-app
    extra_hosts:
      - ethics-sftp-ui_mongodb_1:172.17.0.1
    restart: unless-stopped
